{
 "title": "Triagem de Laudos - API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Latência Média (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum) / sum(http_request_duration_seconds_count)",
     "legendFormat": "latência média"
    }
   ]
  },
  {
   "title": "Taxa de Erro (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(http_requests_total{status_code=~\"4..|5..\"}) / sum(http_requests_total)"
    }
   ]
  }
 ]
}